### ISSUE TITLE
How to avoid a panel to be collapsed by default?

### ISSUE THREAD

**Issue by kghbln** [oetterer/BootstrapComponents#21]
This is probably too easy to figure out.

How can I make a panel not being collapsed by default in an [example like this one?](https://sandbox.semantic-mediawiki.org/wiki/BootstrapComponents/Accordion)

I would have guessed that `active` from the third panel may do the trick however it is not working. Moreover I am a bit irritated that it transforms the wiki's sidebar to show the bullets for the `li` tags.

**Comment by malberts** [comment]
I have a fix for the `active` issue: #25 

However, the `li` issue seems to be caused by having both Medik and Chameleon enabled while using the Accordion component.
![image](https://user-images.githubusercontent.com/1428594/118379495-1766a400-b5db-11eb-892c-ec927480fcff.png)

When disabling Chameleon:
![image](https://user-images.githubusercontent.com/1428594/118379731-d8395280-b5dc-11eb-9898-9c9b3b0bfbcd.png)

It seems like Chameleon is loading its own styles even when it is not the active skin. For example on the SMW sandbox I see this when inspecting the styles:
![image](https://user-images.githubusercontent.com/1428594/118379717-b213b280-b5dc-11eb-85ec-163bbd9f848d.png)
I see the same locally.

**Comment by kghbln** [comment]
> I have a fix for the active issue: #25

Thanks a bunch. I thought that somehow I was doing something wrong.

> It seems like Chameleon is loading its own styles even when it is not the active skin and this combination causes the problem. 

Ah, this explains it. Probably something to address with Chameleon. Not top prio at all since I would think that it is not very likely that one uses both skins at the same time for a wiki.
